# Generated by Django 5.2.15 on 2026-06-29 18:03

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=core.models.feed_photo_path, validators=[core.models.validate_feed_photo]),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='season',
            name='promotions_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='friendlymatchrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('groups_ready', 'Groups ready'), ('group_stage', 'Group stage'), ('knockout', 'Knockout'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('max_participants', models.PositiveIntegerField(default=32)),
                ('groups_generated', models.BooleanField(default=False)),
                ('group_fixtures_generated', models.BooleanField(default=False)),
                ('knockout_generated', models.BooleanField(default=False)),
                ('champion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_wins', to='core.playerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.tournament')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('group', 'Group'), ('round_of_16', 'Round of 16'), ('quarter_final', 'Quarter-final'), ('semi_final', 'Semi-final'), ('final', 'Final')], default='group', max_length=20)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('home_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('played', 'Played')], default='scheduled', max_length=20)),
                ('away_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_away_matches', to='core.playerprofile')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='core.tournamentgroup')),
                ('home_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_home_matches', to='core.playerprofile')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.tournament')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_match_wins', to='core.playerprofile')),
            ],
            options={
                'ordering': ['round_number', 'stage', 'group__name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seed', models.PositiveIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_entries', to='core.playerprofile')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.tournament')),
            ],
            options={
                'ordering': ['seed', 'player__user__username'],
                'unique_together': {('tournament', 'player')},
            },
        ),
        migrations.CreateModel(
            name='NewsReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reaction', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.newspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TournamentGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.tournamentgroup')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='core.tournamentparticipant')),
            ],
            options={
                'ordering': ['group__name', 'participant__player__user__username'],
                'unique_together': {('group', 'participant')},
            },
        ),
    ]
