# Generated by Django 5.2.15 on 2026-06-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_playerprofile_profile_photo_notification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentparticipant',
            options={'ordering': ['status', 'seed', 'player__user__username']},
        ),
        migrations.AddField(
            model_name='tournamentparticipant',
            name='status',
            field=models.CharField(choices=[('selected', 'Selected'), ('reserve', 'Reserve')], default='selected', max_length=20),
        ),
    ]
