# Generated by Django 5.2.15 on 2026-07-05 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_newscomment_tagged_users_newspost_tagged_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentmatch',
            options={'ordering': ['round_number', 'stage', 'group__name', 'bracket_slot', 'id']},
        ),
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('groups_knockout', 'Group stage + knockout'), ('knockout', 'Direct knockout'), ('league', 'Round-robin league')], default='groups_knockout', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='group_legs',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Single round'), (2, 'Home & away')], default=2),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='away_penalties',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='bracket_slot',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='home_penalties',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='stage',
            field=models.CharField(choices=[('group', 'Group'), ('round_of_16', 'Round of 16'), ('quarter_final', 'Quarter-final'), ('semi_final', 'Semi-final'), ('third_place', 'Third place'), ('final', 'Final')], default='group', max_length=20),
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('live', 'Live'), ('ended', 'Ended')], default='live', max_length=10)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('streamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('peer_id', models.CharField(max_length=64)),
                ('target', models.CharField(choices=[('broadcaster', 'Broadcaster'), ('viewer', 'Viewer')], max_length=20)),
                ('kind', models.CharField(max_length=20)),
                ('payload', models.TextField(blank=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='core.livestream')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
