# Generated by Django 5.2.15 on 2026-07-05 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tournamentmatch_options_tournament_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_streams', to='core.match'),
        ),
        migrations.AddField(
            model_name='livestream',
            name='tournament_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_streams', to='core.tournamentmatch'),
        ),
    ]
